Repository Dan6erbond/sk-auth, pull requests merged in 2021-05, with the labels that each got.

#8 [ENHANCEMENT] Demo / Testing App, Updated Build Configuration
  .eslintrc.cjs
  app/.eslintrc.cjs
  app/.gitignore
  app/.npmrc
  app/.prettierignore
  app/.prettierrc
  app/README.md
  app/package.json
  app/postcss.config.cjs
  app/src/app.html
  app/src/app.postcss
  app/src/global.d.ts
  app/src/hooks.ts
  app/src/lib/appAuth.ts
  app/src/routes/__layout.svelte
  app/src/routes/api/auth/[...auth].ts
  app/src/routes/index.svelte
  app/src/routes/login.svelte
  app/src/routes/profile.svelte
  app/static/logo.svg
  app/svelte.config.js
  app/tailwind.config.cjs
  app/tsconfig.json
  app/yarn.lock
  package.json
  res/logo.svg
  src/auth.ts
  src/client/signIn.ts
  src/index.ts
  src/jwt.ts
  src/path.ts
  src/providers/base.ts
  src/providers/facebook.ts
  src/providers/google.ts
  src/providers/index.ts
  src/providers/oauth2.ts
  src/providers/reddit.ts
  src/providers/twitter.ts
  tsconfig.json
  yarn.lock
Labels: bug, enhancement, help wanted

#11 [ENHANCEMENT] Distributable Bundle with Rollup and ESBuild
  app/package.json
  app/src/lib/appAuth.ts
  app/src/routes/__layout.svelte
  app/yarn.lock
  client/package.json
  package-lock.json
  package.json
  providers/package.json
  rollup.config.js
  src/client/signIn.ts
  src/client/signOut.ts
  src/index.ts
  src/jwt.ts
  tsconfig.json
  yarn.lock
Labels: bug, enhancement

#12 [ENHANCEMENT] OAuth Base Provider
  app/src/lib/appAuth.ts
  app/yarn.lock
  src/auth.ts
  src/providers/base.ts
  src/providers/facebook.ts
  src/providers/google.ts
  src/providers/index.ts
  src/providers/oauth2.base.ts
  src/providers/oauth2.ts
  src/providers/reddit.ts
  src/providers/twitter.ts
Labels: enhancement

#16 [ENHANCEMENT] Enhanced Types, Improved OAuth2 Configuration and Bug Fixes
  app/src/lib/appAuth.ts
  src/auth.ts
  src/helpers.ts
  src/providers/base.ts
  src/providers/facebook.ts
  src/providers/google.ts
  src/providers/index.ts
  src/providers/oauth2.base.ts
  src/providers/oauth2.ts
  src/providers/reddit.ts
  src/providers/twitter.ts
Labels: bug, enhancement

#27 [ENHANCEMENT] Build ESM Peer Dependency, Typing & Configs
  app/package.json
  app/src/lib/appAuth.ts
  app/yarn.lock
  package.json
  yarn.lock
Labels: bug, enhancement

#22 added twitch provider
  app/src/global.d.ts
  app/src/lib/appAuth.ts
  app/src/routes/login.svelte
  src/providers/index.ts
  src/providers/twitch.ts
Labels: enhancement

#32 [ENHANCEMENT] Hybrid ESM & CJS Builds
  app/yarn.lock
  client/package.json
  package.json
  providers/package.json
  rollup.config.js
Labels: bug, enhancement
